### ISSUE TITLE
A library cannot be opened by archetypal if gas material names are not gas types

### ISSUE THREAD

**Issue by szvsw** [samuelduchesne/archetypal#355]
https://github.com/samuelduchesne/archetypal/blob/4d734c80b8c5d3588e390c694f0aacc6554b1cef/archetypal/template/materials/gas_material.py#L22-L40

repro:

```
from archetypal import UmiTemplateLibrary
lib = UmiTemplateLibrary.open("<path>/BostonTemplateLibrary_2.json")
gas = lib.GasMaterials[0]
gas.Name = "My Gas"
lib.save("<path>/Library_with_bad_gas.json")
UmiTemplateLibrary.open("<path>/Library_with_bad_gas.json")
```

Output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/src/local/archetypal/archetypal/umi_template.py", line 332, in open
    t = cls.loads(f.read(), name)
  File "/usr/src/local/archetypal/archetypal/umi_template.py", line 342, in loads
    t.GasMaterials = [
  File "/usr/src/local/archetypal/archetypal/umi_template.py", line 343, in <listcomp>
    GasMaterial.from_dict(store, allow_duplicates=True)
  File "/usr/src/local/archetypal/archetypal/template/materials/gas_material.py", line 107, in from_dict
    return cls(id=_id, **data, **kwargs)
  File "/usr/src/local/archetypal/archetypal/template/materials/gas_material.py", line 37, in __init__
    self.Type = Name.upper()
  File "/usr/src/local/archetypal/archetypal/template/materials/gas_material.py", line 51, in Type
    assert value.lower() in self._GASTYPES, (
AssertionError: Invalid value 'MY GAS' for material gas type. Gas type must be one of the following:
('air', 'argon', 'krypton', 'xenon', 'sf6')
```

Non breaking fix would be to try/except using the name first, and then fall back to type?  Or maybe to use the type if it exists in kwargs, and if it doesn't, fall back to name?

**Comment by szvsw** [comment]
Ah so it turns out umi template editor seems to use the name property, and will likely fail if you have gases with custom names even if their type is set correctly.
