### ISSUE TITLE
archetypal convert error

### ISSUE THREAD

**Issue by brynpickering** [samuelduchesne/archetypal#46]
On running ``archetypal convert "SimpleOfficeBuilding.idf" "output"`` I get the following error:

```
Traceback (most recent call last):
  File "my_conda_env/bin/archetypal", line 8, in <module>
    sys.exit(cli())
  File "my_conda_env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "my_conda_env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "my_conda_env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "my_conda_env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "my_conda_env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "my_conda_env/lib/python3.7/site-packages/archetypal/cli.py", line 303, in convert
    if paths:
UnboundLocalError: local variable 'paths' referenced before assignment
```

It looks like in `cli.py` there is a `with` statement which produces a variable `paths` which is then expected to exist later on (`if paths:`). `paths` might need to be set as e.g. None before the `with` statement?

Note: this issue comes to you as part of my wider [JOSS review](https://github.com/openjournals/joss-reviews/issues/1833)

**Comment by samuelduchesne** [comment]
@louisleroy5, I am getting an error when I run `archetypal convert "tests/input_data/trnsys/test_multizone_EP.idf" "tests/.temp"` in the command line inside Pycharm. Can you check this out?

The error is:
```
Traceback (most recent call last):
  File "/Users/samuelduchesne/anaconda3/envs/archetypal/bin/archetypal", line 11, in <module>
    load_entry_point('archetypal', 'console_scripts', 'archetypal')()
  File "/Users/samuelduchesne/anaconda3/envs/archetypal/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/samuelduchesne/anaconda3/envs/archetypal/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/samuelduchesne/anaconda3/envs/archetypal/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/samuelduchesne/anaconda3/envs/archetypal/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/samuelduchesne/anaconda3/envs/archetypal/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/samuelduchesne/Dropbox/Polytechnique/Doc/software/archetypal/archetypal/cli.py", line 294, in convert
    capacitance=capacitance
  File "/Users/samuelduchesne/Dropbox/Polytechnique/Doc/software/archetypal/archetypal/trnsys.py", line 105, in convert_idf_to_trnbuild
    idf_file, window_lib, output_folder, trnsidf_exe, template
  File "/Users/samuelduchesne/Dropbox/Polytechnique/Doc/software/archetypal/archetypal/trnsys.py", line 560, in _assert_files
    raise IOError("idf_file file not found")
OSError: idf_file file not found

```

I am running this on `develop`

**Comment by samuelduchesne** [comment]
Hi @brynpickering, regarding this issue with `archetypal convert`, since you need TRNSYS for it work, please refer to https://github.com/openjournals/joss-reviews/issues/1833#issuecomment-582922979 for a demo.
